### ISSUE TITLE
No reaction when clicking on the streamdeck

### ISSUE THREAD

**Issue by mariuseikenes** [zoton2/node-streamdeck-util#10]
Hey! I'm trying to create my own stream deck software with node.js. I've set things up according to the readme, however nothing happens when clicking the keys.

https://pastebin.com/dB2zgtaE

I'm not really sure what's meant to be under `key` on the `sd.listen`, is it just meant to be DEFAULT_KEY?
Let me know if more information is necessary

I should add I'm using this on Linux (Pop!_os) and its the 15-key version. I'm trying to create my own streamdeck software to handle key inputs

**Comment by zoton2** [comment]
I'm guessing as you closed this it is no longer an issue?

`DEFAULT_KEY` is meant to match whatever string you use on the `streamdeck-plugin` side.

I don't think Elgato have software for Linux, right? As this bundle also requires their software, it won't be much use for you. There's other libraries that re-implement the Stream Deck fully into Node.js without needing their software, but I've not used them myself. [@elgato-stream-deck/node](https://www.npmjs.com/package/@elgato-stream-deck/node) is one of those.
